#!/bin/bash

prompt_user(){

	message=${1:-"Enter the account details"}
	echo "$message"	
	read -p "Enter a username: " user_name
	read -sp "Enter a password: " user_password
	echo ""
	read -sp "Enter the password again: " user_password_check
	echo ""
}

check_user(){
	grep -q \^${1}\: /etc/passwd && return 0
}

if  [ $# -eq 0 ] ; then
	prompt_user

	while [ "$user_password" != "$user_password_check" ] ; do
		prompt_user "Passwords do not match!"
	done
else
	user_name="$1"
	user_password="${2:-Password1}"
fi


while  check_user "$user_name" ; do 
	prompt_user "The username already exists, please select fresh details."
done

echo -e "\n$user_name $user_password"
